name: auto-reviewers-when-pull-request
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: gh pr edit $NUMBER --add-reviewer usami-k
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}

